global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "delineate-app"
    scrape_interval: 5s
    static_configs:
      - targets: ["delineate-app:3000"]

  - job_name: "delineate-worker"
    scrape_interval: 5s
    static_configs:
      - targets: ["delineate-worker:3001"]

  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
